"""Regenerate small, self-hosted Noto Sans SC variable subsets for site copy.

Run after editing Chinese copy: python scripts/subset_fonts.py
Requires npm ci and pip install -r requirements-fonts.txt.
Generated files are committed; production builds do not need Python.
"""
from __future__ import annotations

import json
import re
import shutil
from pathlib import Path

from fontTools import subset
from fontTools.ttLib import TTFont

ROOT = Path(__file__).resolve().parents[1]
PACKAGE = ROOT / "node_modules/@fontsource-variable/noto-sans-sc"
OUTPUT = ROOT / "src/assets/fonts/noto"


def in_ranges(codepoint: int, unicode_range: str) -> bool:
    for token in unicode_range.split(","):
        bounds = token.strip()[2:].split("-")
        start = int(bounds[0], 16)
        end = int(bounds[-1], 16)
        if start <= codepoint <= end:
            return True
    return False


def compact_ranges(codepoints: set[int]) -> str:
    groups: list[str] = []
    ordered = sorted(codepoints)
    start = end = ordered[0]
    for codepoint in ordered[1:]:
        if codepoint == end + 1:
            end = codepoint
        else:
            groups.append(f"U+{start:X}" if start == end else f"U+{start:X}-{end:X}")
            start = end = codepoint
    groups.append(f"U+{start:X}" if start == end else f"U+{start:X}-{end:X}")
    return ",".join(groups)


def main() -> None:
    if not PACKAGE.is_dir():
        raise SystemExit("Run npm ci first: the original Fontsource package is required.")
    sources = sorted([*ROOT.glob("src/**/*.ts"), *ROOT.glob("src/**/*.tsx"), ROOT / "src/i18n/source.json"])
    sources += [ROOT / "index.html", ROOT / "public/site.webmanifest"]
    text = "".join(path.read_text(encoding="utf-8") for path in sources if path.exists())
    wanted = {ord(character) for character in text if ord(character) > 127}
    original_css = (PACKAGE / "wght.css").read_text(encoding="utf-8")
    OUTPUT.mkdir(parents=True, exist_ok=True)
    faces: list[str] = []
    filenames: set[str] = set()
    covered: set[int] = set()
    original_supported: set[int] = set()
    total_bytes = 0
    for face in re.findall(r"@font-face\s*\{[^}]+\}", original_css):
        match = re.search(r"url\(\./files/([^)]+)\)", face)
        ranges = re.search(r"unicode-range:\s*([^;]+)", face)
        if not match or not ranges:
            continue
        filename = match.group(1)
        font = TTFont(PACKAGE / "files" / filename, recalcTimestamp=False)
        available = set(font.getBestCmap())
        selected = {cp for cp in wanted & available if in_ranges(cp, ranges.group(1))}
        original_supported.update(selected)
        if not selected:
            font.close()
            continue
        options = subset.Options()
        options.flavor = "woff2"
        options.recalc_timestamp = False
        options.name_IDs = ["*"]
        options.name_languages = ["*"]
        subsetter = subset.Subsetter(options=options)
        subsetter.populate(unicodes=selected)
        subsetter.subset(font)
        if "fvar" not in font:
            raise RuntimeError(f"Variable weight axis was lost: {filename}")
        target = OUTPUT / filename
        font.save(target)
        font.close()
        with TTFont(target) as check:
            if not selected <= set(check.getBestCmap()):
                raise RuntimeError(f"Character coverage was lost: {filename}")
        covered.update(selected)
        filenames.add(filename)
        total_bytes += target.stat().st_size
        faces.append(
            '@font-face {\n'
            '  font-family: "Noto Sans SC Variable";\n'
            '  font-style: normal;\n'
            '  font-weight: 100 900;\n'
            '  font-display: swap;\n'
            f'  src: url("./{filename}") format("woff2");\n'
            f'  unicode-range: {compact_ranges(selected)};\n'
            '}\n'
        )
    if covered != original_supported:
        raise RuntimeError("Generated fonts do not cover all original available site characters.")
    # Only remove stale generated font files in the explicitly resolved output directory.
    for old in OUTPUT.glob("*.woff2"):
        if old.name not in filenames:
            old.unlink()
    header = "/* Generated by scripts/subset_fonts.py. Regenerate after changing Chinese copy. */\n"
    (OUTPUT / "subset.css").write_text(header + "\n".join(faces), encoding="utf-8")
    shutil.copyfile(PACKAGE / "LICENSE", OUTPUT / "OFL.txt")
    report = {
        "source_font": "@fontsource-variable/noto-sans-sc",
        "source_version": json.loads((PACKAGE / "package.json").read_text())["version"],
        "files": len(filenames),
        "font_bytes": total_bytes,
        "covered_codepoints": len(covered),
        "unsupported_codepoints": [f"U+{cp:X}" for cp in sorted(wanted - covered)],
    }
    print(json.dumps(report, indent=2))


if __name__ == "__main__":
    main()
